### ISSUE TITLE
BinFile maximum_address is actually pointing 1 byte "further"?

### ISSUE THREAD

**Issue by kwesolowski** [eerimoq/bincopy#18]
Not sure if its "an issue" in code, naming or just maybe lack of doc, but maximum_address not maximum address of given file/segment, its behaves closer to end iterator (pointing 1 byte after last one?)

**Comment by eerimoq** [comment]
Yes, exactly, the idea is that it should mimic iterators.

**Comment by eerimoq** [comment]
I guess so...
