### ISSUE TITLE
module entry point is broken

### ISSUE THREAD

**Issue by mzihlmann** [eerimoq/bincopy#23]
after updating 17.9 -> 17.10, bincopy can no longer be used as a module entry point

`
python -m bincopy
`
now returns

`
NameError: name 'main' is not defined
`

i havent investigated the error properly myself, but in bincopy.py there are two `main` shields which looks fishy to me.

https://github.com/eerimoq/bincopy/blob/master/bincopy.py#L321
https://github.com/eerimoq/bincopy/blob/master/bincopy.py#L2017

thank you for your great work!

**Comment by eerimoq** [comment]
True, I accidently added another main(). Will remove it and create a new release.

Thanks for reporting!

**Comment by mzihlmann** [comment]
awesome!! thank you so much! 🏆

**Comment by eerimoq** [comment]
Fix published to PyPI.

**Comment by mzihlmann** [comment]
awesome works!
