### ISSUE TITLE
Incorrect error check condition?

### ISSUE THREAD

**Issue by amkld** [eerimoq/bincopy#28]
Hi
I was checking the code in bincopy.py and I think the `if` condition used to check for non-overlapping segments in `remove_data`  is incorrect:
```python
if ((minimum_address >= self.maximum_address)
            and (maximum_address <= self.minimum_address)):
```
This will only be true in the rare case of trying to remove a zero-length segment from a zero-length segment at the same address which is not what was intended. I think the `and` condition should be changed to `or` i.e.
```python
if ((minimum_address >= self.maximum_address)
            or (maximum_address <= self.minimum_address)):
```

**Comment by eerimoq** [comment]
You don't happen to have an example that trigger the error? It would be very helpful.

**Comment by eerimoq** [comment]
Fixed it and created a new version of the package, 17.10.3. Feel free to test it and let me know if it doesn't work.
