### ISSUE TITLE
as_binary() raises a MemoryError

### ISSUE THREAD

**Issue by E-genin** [eerimoq/bincopy#30]
Hi there, 

I am running the following script : 
```
import bincopy 

f = bincopy.BinFile("Test_2.hex")
print(f.as_binary())
```
I get the following error : 
![image](https://user-images.githubusercontent.com/17356780/197908043-35da57bf-6ae1-4252-bbad-1bcd5de0889a.png)

I noticed that when I reduce the size of the binary file, it works. (the original binary is around 26 KB) 

Thanks in advance

**Comment by eerimoq** [comment]
There are probably huge sections of empty space in your binary. The maximum address is a lot higher than the minimum address.

**Comment by E-genin** [comment]
Thanks @eerimoq for the reply, 

Do you know why should this be a problem ? 
Do you suggest some kind of workaround ?

**Comment by eerimoq** [comment]
It all depends on what you are trying to do. Maybe there are some segments you can remove?

**Comment by E-genin** [comment]
I need to sign the binary, so I don't think I can modify the content or remove blocks.

**Comment by jrast** [comment]
Depending on how you need to sign the binary it might be enough to loop over the individual segments instead of the whole binary. Without any additional information (example file, inforamtion about how to sign, ...) it's hard to guess the correct way.
