### ISSUE TITLE
Invalid section from ELF file

### ISSUE THREAD

**Issue by Gargy007** [eerimoq/bincopy#32]
The BINCOPY create invalid section from ELF file. The ELF file is created in NXP MCUXpresso compiler.

The SREC from BINCOPY contains additional (probably irrelevant) data
Observation: the output contains some data at 0x8000000, while the image is located at 0x80002000.

Used OBJCOPY to validate result:
arm-none-eabi-objcopy.exe -O srec evkbimxrt1050_iled_blinky_sdram.axf evkbimxrt1050_iled_blinky_sdram.srec
Use BINCOPY to unify S record output to simplify comparison:
bincopy convert -i srec -o srec .\evkbimxrt1050_iled_blinky_sdram.srec .\evkbimxrt1050_iled_blinky_sdram.s19

Observation: no data at 0x8000000, the code starts at 0x80002000

Procedure to reproduce:
 - Convert ELF file by bincopy: 
  bincopy convert -i elf -o srec .\evkbimxrt1050_iled_blinky_sdram.axf converted.s19
  
  - Compare result with _evkbimxrt1050_iled_blinky_sdram.s19_ created by "arm-none-eabi-objcopy.exe"
[bincopy.zip](https://github.com/eerimoq/bincopy/files/10722283/bincopy.zip)

**Comment by Gargy007** [comment]
Hello,
 great, it works. One more time - THANK you.

Petr

po 13. 2. 2023 v 19:12 odesílatel Erik Moqvist ***@***.***>
napsal:

**Comment by Gargy007** [comment]
Hi Erik,
 bad news , I run other tests and some other ELF files became problematics.

Please check for example file in attachment, bincopy adds to result Srec or
binary RAM section:

[image: image.png]


This part should not be here :-(

Thank you for your look.

Petr

út 14. 2. 2023 v 6:51 odesílatel Petr Gargulak ***@***.***>
napsal:

**Comment by eerimoq** [comment]
The image is missing. Also, please add a problematic elf-file and correct corresponding srec so I can add a test.

**Comment by Gargy007** [comment]
Sorry , I reply by email and this way remove as picture as attachment :-(

Problematic section in srec:
![image](https://user-images.githubusercontent.com/6661580/218661204-d00cc210-5f7d-4fce-9f0e-5a84385a671e.png)

**Comment by eerimoq** [comment]
```
readelf -S -W gcc.elf
...
  [ 7] .data             PROGBITS        1fff0000 020000 00006c 00  WA  0   0  4
...
```

Looks like that part should be included in the srec.

**Comment by Gargy007** [comment]
This part cannot be included in programming script - those addresses are in RAM. And top of that bincopy-17.14.0 doesn't do that. In this version the Bincopy handle this file correctly.

**Comment by eerimoq** [comment]
Please try latest commit on master branch. I implemented it in a hurry, so it is probably not correct. Feel free to submit a PR is you can figure out how to fix it.

**Comment by Gargy007** [comment]
Something gets better , something is worse :-( 

I created golden set and examples of elf file and it binary images, maybe it's helps ...
[gold_samples_bincopy.zip](https://github.com/eerimoq/bincopy/files/10732035/gold_samples_bincopy.zip)

Test case is easy just convert provided ELF file to binary and compare to provided "good" results.

**Comment by eerimoq** [comment]
Did youu test with latest master?

Den tis 14 feb. 2023 12:53Gargy007 ***@***.***> skrev:

**Comment by Gargy007** [comment]
Yes I did :-(
 Just take a look at sizes of binary - *_bincopy.bin versus golden samples that I already sent:
 
![image](https://user-images.githubusercontent.com/6661580/218746336-39f7650e-6bf1-44cb-b077-9677cfe3f1e5.png)

**Comment by eerimoq** [comment]
gcc and iar looks good in latest release (17.14.3). Not sure about keil. Seems like a data section is missing in the output file.

**Comment by Gargy007** [comment]
Hello, as you wrote, IAR, GCC is OK but KEIL is not :-( . 

I retest BINCOPY 17.14.0 version and under that all three compilers works fine. It will be great to find combination that all those three golden samples works fine and also the original use case from this issue. 

https://github.com/eerimoq/bincopy/files/10732035/gold_samples_bincopy.zip
https://github.com/eerimoq/bincopy/files/10722283/bincopy.zip

**Comment by eerimoq** [comment]
Any chance you can help out trying to fix the issue? It's just a few lines of code to extract data from elf-files, so should be easy to understand and edit. Just have a look at the changes in the last couple of commits. I think more test cases are key to making this work. Also, reading the ELF specification and possibly compiler/linker quirks.

**Comment by Gargy007** [comment]
Let me solve some own issues :-) and I try to look at it

**Comment by eerimoq** [comment]
Give 17.14.5 a try.

**Comment by Gargy007** [comment]
Today morning I wanted to try to find the issue, but you was faster.

This version works on all my samples. Thanks

**Comment by eerimoq** [comment]
I'm sure more issues will appear. It's probably impossible to make it work for all toolchains and linker scripts.
