### ISSUE TITLE
Chunk.__len__ should return length of data

### ISSUE THREAD

**Issue by bessman** [eerimoq/bincopy#36]
```python
import bincopy
hexdata = bincopy("myfile.hex")
print(len(next(hexdata.segments.chunks(size=32))))
```
```python
2
```

I find this surprising. Anyone doing `len(chunk)` probably wants the length of its `data` member, not the fact that it's a two-tuple. I propose implementing `Chunk` like so:

```python
class Chunk(namedtuple("Chunk", ["address", "data"])):  # Or _Chunk, depending on outcome of #35
    def __len___(self):
        return len(self.data)
```

While this would *technically* change the API, I argue that it is extremely unlikely to break anything; anyone doing `len(chunk)` almost certainly means `len(chunk.data)`.

**Comment by eerimoq** [comment]
Good suggestion. Part of version 18.0.0.
