### ISSUE TITLE
First chunk is misaligned if segment has non-aligned start address

### ISSUE THREAD

**Issue by bessman** [eerimoq/bincopy#40]
```python
records = """
    :02000004000AF0
    :10B8440000000000000000009630000007770000B0
"""
hexfile = bincopy.BinFile()
hexfile.add_ihex(records)
align = 8
chunks = hexfile.segments.chunks(size=16, alignment=align)
assert not any(c.address % align for c in chunks)
```

IMO, the first chunk should be padded such that it is also aligned.

**Comment by eerimoq** [comment]
I haven't given it much thought, but I noticed that the length of the padding parameter to [as_binary()](https://github.com/eerimoq/bincopy/blob/master/bincopy.py#L1437-L1455) depends on word size. If possible, padding parameters across the library should be consistent. Is it possible to make the new padding parameter word size dependent?

**Comment by bessman** [comment]
Done.
