### ISSUE TITLE
Package permissions issue

### ISSUE THREAD

**Issue by bobbycNH** [eerimoq/bincopy#6]
I'm having a weird issue that, to be honest, I can't imagine how it's a bincopy issue but it doesn't appear to affect any other packages.  When our admin bootstraps a Windows machine he installs bincopy (and several other packages).  Later, a user runs python and attempts to run `import bincopy` and gets an `ImportError`.  Logging in as admin, I can successfully perform the import.  

We suspected it was a permissions error so we tested our theory by changing the owner of the Libs directory to the present user (recursively) and ensuring proper permissions were set, but it made no difference.  We then logged in as admin and removed bincopy (`pip uninstall bincopy`), then reinstalled as the user account (`pip install bincopy`) and everything worked fine.  In both cases bincopy was installed into `C:\Python27\Libs\site-packages` which is in the search path for both users.

I looked through the package and can't find anything that should be affected by installing user.  Have you seen anything like this?  I have been installing and using bincopy under Linux for a while without any such issues.

**Comment by eerimoq** [comment]
No,  I've not had any problems to import bincopy in Linux nor Windows.

Was the error message ``ImportError: No module named bincopy``? In that case it really sounds like a path problem. If you didn't already, print ``sys.path`` to get a list of the paths that are searched when importing a module.

**Comment by bobbycNH** [comment]
Yeah, I thought the same thing but I verified that both users were installing into `C:\Python27\Libs\site-packages` so I can't figure how anything could go wrong.  Just to double check, I verified that both path users have site-packages in `sys.path`.  

Weird.
